### PR TITLE
Drop node.js 4 support and update dev deps

### PR DESCRIPTION
**Pull request by papandreou**

### CODE REVIEW

**Comment by alexjeffburke** [comment]
@papandreou I've fixed the merge conflict and also bumped pem to the node 6+ version while we're here - that means our story is 12+ will be 6 only and we can easily fix any bug on the current release.

**Comment by papandreou** [comment]
@alexjeffburke, thanks a bunch! Does it look good to you, all in all? Because then I think we should get it released.

**Comment by alexjeffburke** [comment]
@papandreou let's go for it 👍

I will just note that if we prettier (very keep to do so) I'd prefer to do it on v11 and merge that to master - that way we can continue to fix bugs across both. What do you think?

**Comment by papandreou** [comment]
Fair! And good idea, we should introduce prettier. I'll work on that.

**Pull request merged**
