### PR TITLE
Unfork mitm by using another workaround

### PR DESCRIPTION
**Pull request by papandreou**
Use the suggestion posted [here](https://github.com/moll/node-mitm/issues/14#issuecomment-437388337) to avoid maintaining a fork of the mitm module.

Most of the diff is due to prettier's reformatting, so I recommend ignoring whitespace changes when viewing it.

### CODE REVIEW

**Comment by alexjeffburke** [comment]
Oh, Cool! Nice that we can get the surface area down.

Once question though, rather than shift around that huge block fo code, could we take the opportunity to just have it as a `function onRequest() {}` or something and then wire it to `mitm.on('request', createSerialized((onReqeust))`? I'm happy to attempt the change and push it to this PR too :)

**Comment by papandreou** [comment]
You're welcome to do that! It's not really a huge piece of code that can be shared, so I didn't feel it was a necessity.

**Comment by papandreou** [comment]
@alexjeffburke, we can also merge this as-is and do further refactorings separately?

**Comment by alexjeffburke** [comment]
Yeah, go for it and get a patch release out :)

**Comment by papandreou** [comment]
Released in 13.3.1

**Pull request merged**
