### PR TITLE
Use raw data in response function connection hook to build mockResponse.

### PR DESCRIPTION
**Pull request by alexjeffburke**
This is some hairy code - but what it does is hook at a very low level to response generation when using response functions and capture the raw data (which ends up as a Buffer). This is then passed directly to the messy.HttpReesponse() constructor for parsing of the complete response.

### CODE REVIEW

**Comment by papandreou** [comment]
Looks sound. A test would probably help me understand it better :). I'm fine with pulling it in as-is, though.

**Comment by alexjeffburke** [comment]
Hey, there is no test because nothing changes ;) What this does is use messy to parse the complete HTTP response buffer as generated by the response function. :)

**Comment by papandreou** [comment]
I guess I just imagined that it would enable us to handle some edge cases that weren't possible before.

Still, :+1:

**Comment by alexjeffburke** [comment]
Haha well hmm that's an interesting thought - happy to have think about that!

**Comment by papandreou** [comment]
Great -- feel free to merge when you think it's ready :)

**Pull request merged**
